### ISSUE TITLE
Missing Offer Management API reference

### ISSUE THREAD

**Issue by alexminza** [vtexdocs/dev-portal-content#218]
Only [Create Channel API](https://developers.vtex.com/docs/api-reference/marketplace-apis#post-/portal.-environment-.com.br/api/sent-offers/channels) is documented.

Missing:
- List channels API
- Update channel API
- Delete channel API

Reference: https://developers.vtex.com/docs/guides/sent-offers-integration-guide-connectors

**Comment by jumeyermattosarruda** [comment]
Hey Alex! Thanks for sharing with us your issue. I'll look into to it, and update you through this thread.

(This is the first issue we receive from users, so our team is super glad that you used this resource!)

**Comment by jumeyermattosarruda** [comment]
Hey Alex! 
So these calls are not documented in our API Reference, nor mentioned in the [Integration Guide](https://developers.vtex.com/docs/guides/sent-offers-integration-guide-connectors) because they aren't actually available for use. We only have the operation [POST Create Channel](https://developers.vtex.com/docs/api-reference/marketplace-apis#post-/portal.-environment-.com.br/api/sent-offers/channels) for this endpoint. If you try to perform GET/PUT/DELETE calls for the url `/api/sent-offers/channels`, you will receive 400 type errors.
 
I checked with the developers responsible for Offer Management, and they confirmed that there are no GET/PUT/DELETE operations available for the endpoint, and creating them is not on our roadmap for now. If you wish to update or retrieve information about channels created, you can do so through a support ticket. 

> But as a reminder, this integration guide should be followed by marketplaces not hosted on VTEX that wish to become an available channel in the [Offer Management module](https://help.vtex.com/tutorial/offer-management--7MRb9S78aBdZjFGpbuffpE) in the VTEX Admin. VTEX marketplaces are automatically included as available channels there, so there's no need to follow this guide if your store is already hosted in VTEX.

I've already updated our Integration guide to include those details as seen in the linked PR, it should be up in a few hours. Thank you for helping us improve our docs!
